name = ""
account_id = ""
route = ""
zone_id = ""
workers_dev = true
type = "webpack"
webpack_config = "node_modules/@ampproject/cloudflare-optimizer-scripts/webpack.config.js"

[env.dev]
vars = { MODE = "dev" }

[env.beta]
vars = { MODE = "beta" }

[env.prod]
vars = { MODE = "prod" }

