name = "optimizer"
type = "webpack"
account_id = "d23423cc1d5bd44271dba1eeadd89fb7"
workers_dev = true
route = ""
zone_id = ""
webpack_config = "webpack.config.js"
vars = { MODE = "production" }
kv_namespaces = [
  { binding = "KV", id = "471b51eb82a14c4382577ca2b2f06113", preview_id="471b51eb82a14c4382577ca2b2f06113"},
]

[env.dev]
vars = { MODE = "dev" }

[env.beta]
name = "optimizer-beta"
vars = { MODE = "beta" }
kv_namespaces = [
  { binding = "KV", id = "2aa2540e31a8499ebc6cb23bfcde6541", preview_id="2aa2540e31a8499ebc6cb23bfcde6541"},
]
