name = ""
type = "webpack"
account_id = ""
workers_dev = true
route = ""
zone_id = ""
webpack_config = "node_modules/@ampproject/cloudflare-optimizer-scripts/webpack.config.js"
kv_namespaces = [
  { binding = "KV", id = "", preview_id=""},
]

[env.dev]
vars = { MODE = "dev" }
kv_namespaces = [
  { binding = "KV", id = "", preview_id=""},
]

[env.beta]
vars = { MODE = "beta" }
kv_namespaces = [
  { binding = "KV", id = "", preview_id=""},
]

[env.prod]
vars = { MODE = "prod" }
kv_namespaces = [
  { binding = "KV", id = "", preview_id=""},
]

